### ISSUE TITLE
LEAP 4.0.3 - Long startup time after upgrade to 4.0.3.

### ISSUE THREAD

**Issue by CryptoBloks** [AntelopeIO/leap#1331] opened 2023-06-22 06:54 UTC
Fresh install of LEAP 4.0.3 on Ubuntu 22.04.2 LTS

API, P2P, and SHIP services enabled on node.
Full block log of ~60mm blocks.
Synced from genesis with stride set for 1,000 blocks with unlimited retention (blocks, state history, and trace strides are all set the same).

Segment of the startup logs with timestamps where the slowdown occurred:
```
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'GET_SENDER' (with digest of 'f0af56d2c5a48d60a4a5b5c903edfb7db3a736a94ed589d0b797df33ff9d3e1d') is enabled with preactivation required
info  2023-06-22T06:14:49.478 nodeos    block_log.cpp:666             open                 ] Log has 808 blocks
info  2023-06-22T06:14:49.487 nodeos    code_cache.cpp:294            code_cache_base      ] EOS VM Optimized Compiler code cache loaded with 27 entries; 1071462736 of 1073741824 bytes free
info  2023-06-22T06:14:49.533 nodeos    log.hpp:713                   open_log             ] trace_history.log has blocks 60846001-60846139
info  2023-06-22T06:28:45.856 nodeos    log.hpp:713                   open_log             ] chain_state_history.log has blocks 60846001-60846139
warn  2023-06-22T06:41:16.334 nodeos    net_api_plugin.cpp:79         plugin_initialize    ] 
```
Process started at 2023-06-22T06:00:35.066
Process completed startup at 2023-06-22T06:41:18.583

Startup took approximately 40 minutes from process start, to first p2p traffic logged.

If server load is interrupted during startup, indexes and state are left inconsistent (dirty database flag set), requiring replay, restart from a recent snapshot, or resync/restore.

**Comment by heifner** [comment] 2023-06-22 11:36
Can you provide command line and config.ini. What chain?

**Comment by CryptoBloks** [comment] 2023-06-22 15:52
The logs above are from a Libre Mainnet SHIP node fresh built with 4.0.3 and synced sing the same version.

I also received similar startup times from a Libre Testnet SHIP node:


`info  2023-06-22T07:00:17.938 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'GET_SENDER' (with digest of 'f0af56d2c5a48d60a4a5b5c903edfb7db3a736a94ed589d0b797df33ff9d3e1d') is enabled with preactivation required
info  2023-06-22T07:12:47.461 nodeos    block_log.cpp:666             open                 ] Log has 238 blocks
info  2023-06-22T07:12:47.463 nodeos    code_cache.cpp:294            code_cache_base      ] EOS VM Optimized Compiler code cache loaded with 36 entries; 1070358736 of 1073741824 bytes free
info  2023-06-22T07:12:47.496 nodeos    log.hpp:713                   open_log             ] trace_history.log has blocks 59290001-59290564
info  2023-06-22T07:25:56.189 nodeos    log.hpp:713                   open_log             ] chain_state_history.log has blocks 59290001-59290564
warn  2023-06-22T07:37:30.406 nodeos    net_api_plugin.cpp:79         plugin_initialize    ] 
`

Node starts using a script that calls a function using configuration variables set in the config.ini (chain specific), and a node specific set of data elements.


`function p2p.api.ship.start {
    echo -e "### STARTING: p2p.api.ship.start";
    local node_role="p2p.api.ship"
    echo -e "ROLE: ${node_role}\n";
    cd ${NODE_ROOT}
    #Set ulimit
    ulimit -n 65535
    ulimit -s 64000
    
    echo -e "Starting ${BLOCKCHAIN} ${NETWORK} P2P, API and SHIP Services";
    ${NODE_BIN_DIR}/nodeos \
      -e -p ${BP_ACCOUNT} \
      --data-dir ${NODE_ROOT} \
      --config-dir ${NODE_ROOT} \
      --config ${NODE_CONFIG} \
      --plugin eosio::net_plugin \
      	--agent-name ${AGENT_NAME} \
    	--p2p-listen-endpoint ${SERVER_P2P_LISTEN} \
    	--p2p-server-address ${SERVER_P2P_ADDRESS} \
      --plugin eosio::state_history_plugin \
    	--state-history-dir state-history \
    	--trace-history \
    	--chain-state-history \
    	--disable-replay-opts \
    	--state-history-endpoint ${SERVER_SHIP_ADDRESS} \
      --plugin eosio::http_plugin \
      	--http-server-address ${SERVER_HTTP_ADDRESS} \
      --plugin eosio::chain_plugin \
        --enable-account-queries true \
        --eos-vm-oc-enable \
        --eos-vm-oc-compile-threads 4 \
      "$@" > ${NODE_LOG_DIR}/${LOG_STDOUT_FILE} 2> ${NODE_LOG_DIR}/${LOG_ERROR_FILE} & echo $! > ${NODE_ROOT}/node.pid
    # Set ROLE flag
    node.role.remove
    node.role.set ${node_role}
    # Start LogXML
#    logxml.start                                        ### @@@ Need to implement
    echo -e "Started ${BLOCKCHAIN} ${NETWORK} P2P, API and SHIP Services";
    echo -e "### COMPLETE: p2p.api.ship.start";
}`


config.ini contains:


`###########################################################################
#
# Nodeos Config Script 
# Created by CryptoBloks.io
# Version 3.0 (20220908.01)
#
###########################################################################

###########################################################################
### Node Options ##########################################################
###########################################################################

## Configured in ./config.node.ini

###########################################################################
### Chain API Plugin ######################################################
###########################################################################
plugin = eosio::http_plugin
plugin = eosio::chain_api_plugin
http-validate-host = false
http-threads = 6
access-control-allow-origin = *
access-control-allow-headers = Origin, X-Requested-With, Content-Type, Accept
http-max-response-time-ms = 1000
verbose-http-errors = true
## enable-account-queries set in API startup command(s) (see $HOST_ROOT/sharedfunctions.sh)

###########################################################################
### Chain Plugin ##########################################################
###########################################################################
plugin = eosio::chain_plugin
abi-serializer-max-time-ms = 75000
chain-state-db-size-mb = 32768                  # Main: 32768 | Test: 16384
chain-threads = 8
sync-fetch-span = 10000                         # Fast Resync

###########################################################################
## Net Plugin #############################################################
###########################################################################
plugin = eosio::net_plugin
plugin = eosio::net_api_plugin                  # Filter/block /v1/net from public access
net-threads = 8
max-clients = 150                               # Public P2P: 150 | BP: 5
p2p-max-nodes-per-host = 100                    # 100 when behind a proxy

###########################################################################
## Producer ###############################################################
###########################################################################
#plugin = eosio::producer_plugin
plugin = eosio::producer_api_plugin             # Filter/block /v1/producer from public access
# producer-name = Modify in ./config.node.ini, set at runtime
# signature-provider = Modify in ./config.node.ini, set at runtime
pause-on-startup = true
last-block-time-offset-us = -300000           # 300 ms Explicit

###########################################################################
## Stride #################################################################
###########################################################################

## Retained Blocks Stride
blocks-log-stride = 1000
blocks-retained-dir = retained
#max-retained-block-files =

## Retained State History Stride
state-history-stride = 1000
state-history-retained-dir = retained

## Trace API Stride
trace-slice-stride = 1000

###########################################################################
### Peer List #############################################################
###########################################################################

### sync list for ...

## p2p.libre.cryptobloks.io
p2p-peer-address = p2p.libre.cryptobloks.io:9876`


Specific variables from from the config.node.ini config file:


`# Begin Node Environment Variables
##NODE=""                           # Lowercase Node Name - Enable to override HOST default
BLOCKCHAIN="libre"                  # Name of blockchain
NETWORK="mainnet"                   # Network Name (mainnet/testnet)
NODE_TYPE="api"                     # Type of Node (api/producer)
NODE_SERVICES="p2p.api.ship"        # Services to run on Node (p2p, api, ship)
SERVER_WALLET_BIND="127.0.0.1"      # Usually localhost
SERVER_WALLET_PORT="3000"           # Usually 3000
SERVER_HTTP_BIND="0.0.0.0"          # Localhost on BP Node, Private address for API Node
SERVER_HTTP_PORT="8888"             # Depends on assignment
SERVER_SHIP_BIND="0.0.0.0"          # Localhost on BP Node, Private address for API Node
SERVER_SHIP_PORT="8088"             # Depends on assignment
SERVER_P2P_BIND="0.0.0.0"           # Usually 0.0.0.0 to listen on Public, Private, and Localhost
SERVER_P2P_PORT="9878"              # Depends on assignment
NODE_CONFIG="config.ini"            # Base config file for Node - Usually config.ini
NODE_VERSION="leap-4.0.3"           # Version of nodeos running
BP_URL="https://bp.cryptobloks.io"  # URL of BP Site Containing bp.json and other required files
BP_LOC="840"                        # Numeric location for BP
BP_SIGNING_PRI_KEY="null"           # Private Signing Key for BP
BP_SIGNING_PUB_KEY="null"           # Public Signing Key for BP
BP_ACCOUNT="cryptobloks"            # BP Account Name
BP_PERMISSION="producer"            # BP Account Privilege Used for Chain Transactions
# End Node Environment Variables`

**Comment by CryptoBloks** [comment] 2023-06-22 15:58
config.ini contains:


`###########################################################################
#
# Nodeos Config Script 
# Created by CryptoBloks.io
# Version 3.0 (20220908.01)
#
###########################################################################

###########################################################################
### Node Options ##########################################################
###########################################################################

## Configured in ./config.node.ini

###########################################################################
### Chain API Plugin ######################################################
###########################################################################
plugin = eosio::http_plugin
plugin = eosio::chain_api_plugin
http-validate-host = false
http-threads = 6
access-control-allow-origin = *
access-control-allow-headers = Origin, X-Requested-With, Content-Type, Accept
http-max-response-time-ms = 1000
verbose-http-errors = true
## enable-account-queries set in API startup command(s) (see $HOST_ROOT/sharedfunctions.sh)

###########################################################################
### Chain Plugin ##########################################################
###########################################################################
plugin = eosio::chain_plugin
abi-serializer-max-time-ms = 75000
chain-state-db-size-mb = 32768                  # Main: 32768 | Test: 16384
chain-threads = 8
sync-fetch-span = 10000                         # Fast Resync

###########################################################################
## Net Plugin #############################################################
###########################################################################
plugin = eosio::net_plugin
plugin = eosio::net_api_plugin                  # Filter/block /v1/net from public access
net-threads = 8
max-clients = 150                               # Public P2P: 150 | BP: 5
p2p-max-nodes-per-host = 100                    # 100 when behind a proxy

###########################################################################
## Producer ###############################################################
###########################################################################
#plugin = eosio::producer_plugin
plugin = eosio::producer_api_plugin             # Filter/block /v1/producer from public access
# producer-name = Modify in ./config.node.ini, set at runtime
# signature-provider = Modify in ./config.node.ini, set at runtime
pause-on-startup = true
last-block-time-offset-us = -300000           # 300 ms Explicit

###########################################################################
## Stride #################################################################
###########################################################################

## Retained Blocks Stride
blocks-log-stride = 1000
blocks-retained-dir = retained
#max-retained-block-files =

## Retained State History Stride
state-history-stride = 1000
state-history-retained-dir = retained

## Trace API Stride
trace-slice-stride = 1000

###########################################################################
### Peer List #############################################################
###########################################################################

### sync list for ...

## p2p.libre.cryptobloks.io
p2p-peer-address = p2p.libre.cryptobloks.io:9876`

**Comment by CryptoBloks** [comment] 2023-06-22 15:59
Specific variables from from the config.node.ini config file:


```
# Begin Node Environment Variables
##NODE=""                           # Lowercase Node Name - Enable to override HOST default
BLOCKCHAIN="libre"                  # Name of blockchain
NETWORK="mainnet"                   # Network Name (mainnet/testnet)
NODE_TYPE="api"                     # Type of Node (api/producer)
NODE_SERVICES="p2p.api.ship"        # Services to run on Node (p2p, api, ship)
SERVER_WALLET_BIND="127.0.0.1"      # Usually localhost
SERVER_WALLET_PORT="3000"           # Usually 3000
SERVER_HTTP_BIND="0.0.0.0"          # Localhost on BP Node, Private address for API Node
SERVER_HTTP_PORT="8888"             # Depends on assignment
SERVER_SHIP_BIND="0.0.0.0"          # Localhost on BP Node, Private address for API Node
SERVER_SHIP_PORT="8088"             # Depends on assignment
SERVER_P2P_BIND="0.0.0.0"           # Usually 0.0.0.0 to listen on Public, Private, and Localhost
SERVER_P2P_PORT="9878"              # Depends on assignment
NODE_CONFIG="config.ini"            # Base config file for Node - Usually config.ini
NODE_VERSION="leap-4.0.3"           # Version of nodeos running
BP_URL="https://bp.cryptobloks.io"  # URL of BP Site Containing bp.json and other required files
BP_LOC="840"                        # Numeric location for BP
BP_SIGNING_PRI_KEY="null"           # Private Signing Key for BP
BP_SIGNING_PUB_KEY="null"           # Public Signing Key for BP
BP_ACCOUNT="cryptobloks"            # BP Account Name
BP_PERMISSION="producer"            # BP Account Privilege Used for Chain Transactions
# End Node Environment Variables
```

**Comment by heifner** [comment] 2023-06-22 16:29
> Also, producer API plugin is running on this node in order to create snapshots. Please consider this a vote for moving that function out of the producer API.

See #1137 which will be in 5.0: https://github.com/AntelopeIO/leap/pull/1137

**Comment by heifner** [comment] 2023-06-22 16:30
How does this startup time compare to 3.x or whatever previous version you used?

**Comment by CryptoBloks** [comment] 2023-06-22 16:41
I've not performed a startup in 3.x in quite some time.  4.0.1 startup is/was roughly 15 seconds.

Those systems have a stride length of 500000, so it's may not be a direct comparison.

Watching disk stats during startup shows steady read bandwidth between 10k and 5M per second, and around 800-900 read operations per second.  Nothing crazy, but it clearly is reading data the entire time it's starting up.

CPU and RAM utilization is also low during this time.  In the range of 2-4% CPU and less than 1% of system RAM.

![image](https://github.com/AntelopeIO/leap/assets/93884436/22bac59d-c0bb-4a05-9239-f635e14de4ac)

**Comment by CryptoBloks** [comment] 2023-06-22 16:48
During startup, does nodeos scan all the retained blocks like slices?

**Comment by heifner** [comment] 2023-06-22 16:54
> If server load is interrupted during startup, indexes and state are left inconsistent (dirty database flag set), requiring replay, restart from a recent snapshot, or resync/restore.

Interrupted via ctrl-c or SIGTERM or interrupted via kill -9 SIGKILL? That is expected for a SIGKILL. It is not expected for a SIGTERM.

**Comment by heifner** [comment] 2023-06-22 17:03
If you didn't startup with a snapshot, the startup is most likely because of the `--enable-account-queries true`. I'm not familiar with Libre, so not sure if that chain has a large # of accounts.

**Comment by CryptoBloks** [comment] 2023-06-22 17:11
> If you didn't startup with a snapshot, the long startup time is most likely because of the `--enable-account-queries true`. I'm not familiar with Libre, so not sure if that chain has a large # of accounts.

Libre Mainnet has about half a million accounts, and is just under a year from genesis.  It looks like the account query DB is being generated in about 1 second:


```
info  2023-06-22T06:41:16.339 nodeos    chain_plugin.cpp:1123         plugin_startup       ] Blockchain started; head block is #60846139
info  2023-06-22T06:41:16.339 nodeos    account_query_db.cpp:143      build_account_query_ ] Building account query DB
info  2023-06-22T06:41:17.809 nodeos    account_query_db.cpp:163      build_account_query_ ] Finished building account query DB in 1.46961000000000008
info  2023-06-22T06:41:17.809 nodeos    chain_api_plugin.cpp:115      plugin_startup       ] starting chain_api_plugin
```

**Comment by heifner** [comment] 2023-06-22 17:13
Can you provide you full startup log. Bonus if you can enable debug logging.

**Comment by CryptoBloks** [comment] 2023-06-22 17:14
> Can you provide you full startup log. Bonus if you can enable debug logging.

Yep, see you back here in about an hour :)

**Comment by CryptoBloks** [comment] 2023-06-22 17:19
This is the full startup log from the original issue report:


```
info  2023-06-22T06:00:35.066 nodeos    chain_plugin.cpp:476          plugin_initialize    ] initializing chain plugin
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:835    operator()           ] Support for builtin protocol feature 'PREACTIVATE_FEATURE' (with digest of '0ec7e080177b2c02b278d5088611686b49d739925a92d9bfcacd7fc6b74053bd') is enabled without activation restrictions
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'ONLY_LINK_TO_EXISTING_PERMISSION' (with digest of '1a99a59d87e06e09ec5b028a9cbb7749b4a5ad8819004365d02dc4379a8b7241') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'FORWARD_SETCODE' (with digest of '2652f5f96006294109b3dd0bbde63693f55324af452b799ee137a81a905eed25') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'WTMSIG_BLOCK_SIGNATURES' (with digest of '299dcb6af692324b899b39f16d5a530a33062804e41f09dc97e9f156b4476707') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'GET_BLOCK_NUM' (with digest of '35c2186cc36f7bb4aeaf4487b36e57039ccf45a9136aa856a5d569ecca55ef2b') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'REPLACE_DEFERRED' (with digest of 'ef43112c6543b88db2283a2e077278c315ae2c84719a8b25f25cc88565fbea99') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'NO_DUPLICATE_DEFERRED_ID' (with digest of '4a90c00d55454dc5b059055ca213579c6ea856967712a56017487886a4d4cc0f') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'RAM_RESTRICTIONS' (with digest of '4e7bf348da00a945489b2a681749eb56f5de00b900014e137ddae39f48f69d67') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'WEBAUTHN_KEY' (with digest of '4fca8bd82bbd181e714e283f83e1b45d95ca5af40fb89ad3977b653c448f78c2') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'BLOCKCHAIN_PARAMETERS' (with digest of '5443fcf88330c586bc0e5f3dee10e7f63c76c00249c87fe4fbf7f38c082006b4') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'DISALLOW_EMPTY_PRODUCER_SCHEDULE' (with digest of '68dcaa34c0517d19666e6b33add67351d8c5f69e999ca1e37931bc410a297428') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'CRYPTO_PRIMITIVES' (with digest of '6bcb40a24e49c26d0a60513b6aeb8551d264e4717f306b81a37a5afb3b47cedc') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'ONLY_BILL_FIRST_AUTHORIZER' (with digest of '8ba52fe7a3956c5cd3a656a3174b931d3bb2abb45578befc59f283ecd816a405') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'RESTRICT_ACTION_TO_SELF' (with digest of 'ad9e3d8f650687709fd68f4b90b41f7d825a365b02c23a636cef88ac2ac00c43') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'GET_CODE_HASH' (with digest of 'bcd2a26394b36614fd4894241d3c451ab0f6fd110958c3423073621a70826e99') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'ACTION_RETURN_VALUE' (with digest of 'c3a6138c5061cf291310887c0b5c71fcaffeab90d5deb50d3b9e687cead45071') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'CONFIGURABLE_WASM_LIMITS2' (with digest of 'd528b9f6e9693f45ed277af93474fd473ce7d831dae2180cca35d907bd10cb40') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'FIX_LINKAUTH_RESTRICTION' (with digest of 'e0fb64b1085cc5538970158d05a009c24e276fb94e1a0bf6a528b48fbc4ff526') is enabled with preactivation required
info  2023-06-22T06:00:35.089 nodeos    protocol_feature_manag:822    operator()           ] Support for builtin protocol feature 'GET_SENDER' (with digest of 'f0af56d2c5a48d60a4a5b5c903edfb7db3a736a94ed589d0b797df33ff9d3e1d') is enabled with preactivation required
info  2023-06-22T06:14:49.478 nodeos    block_log.cpp:666             open                 ] Log has 808 blocks
info  2023-06-22T06:14:49.487 nodeos    code_cache.cpp:294            code_cache_base      ] EOS VM Optimized Compiler code cache loaded with 27 entries; 1071462736 of 1073741824 bytes free
info  2023-06-22T06:14:49.533 nodeos    log.hpp:713                   open_log             ] trace_history.log has blocks 60846001-60846139
info  2023-06-22T06:28:45.856 nodeos    log.hpp:713                   open_log             ] chain_state_history.log has blocks 60846001-60846139
warn  2023-06-22T06:41:16.334 nodeos    net_api_plugin.cpp:79         plugin_initialize    ] 
**********SECURITY WARNING**********
*                                  *
* --         Net API            -- *
* - EXPOSED to the LOCAL NETWORK - *
* - USE ONLY ON SECURE NETWORKS! - *
*                                  *
************************************

info  2023-06-22T06:41:16.334 nodeos    producer_plugin.cpp:1084      plugin_initialize    ] Subjective CPU billing disabled
info  2023-06-22T06:41:16.335 nodeos    producer_plugin.cpp:1186      plugin_initialize    ] read-only-threads 0, max read-only trx time to be enforced: 30000 us
warn  2023-06-22T06:41:16.339 nodeos    producer_api_plugin.cp:163    plugin_initialize    ] 
**********SECURITY WARNING**********
*                                  *
* --        Producer API        -- *
* - EXPOSED to the LOCAL NETWORK - *
* - USE ONLY ON SECURE NETWORKS! - *
*                                  *
************************************

info  2023-06-22T06:41:16.339 nodeos    resource_monitor_plugi:73     plugin_initialize    ] Monitoring interval set to 2
info  2023-06-22T06:41:16.339 nodeos    resource_monitor_plugi:89     plugin_initialize    ] Space usage threshold set to 90%
info  2023-06-22T06:41:16.339 nodeos    resource_monitor_plugi:99     plugin_initialize    ] Shutdown flag when threshold exceeded set to true
info  2023-06-22T06:41:16.339 nodeos    resource_monitor_plugi:106    plugin_initialize    ] Warning interval set to 30
info  2023-06-22T06:41:16.339 nodeos    main.cpp:142                  main                 ] nodeos version v4.0.3 v4.0.3-6e2bc2ee3ecc759fff3660cbfd3b843c8a714cb8
info  2023-06-22T06:41:16.339 nodeos    main.cpp:143                  main                 ] nodeos using configuration file [path removed]/libre/mainnet/config.ini
info  2023-06-22T06:41:16.339 nodeos    main.cpp:144                  main                 ] nodeos data directory is [path removed]/libre/mainnet
info  2023-06-22T06:41:16.339 nodeos    controller.cpp:559            replay               ] no irreversible blocks need to be replayed
info  2023-06-22T06:41:16.339 nodeos    controller.cpp:575            replay               ] 0 reversible blocks replayed
info  2023-06-22T06:41:16.339 nodeos    controller.cpp:585            replay               ] replayed 0 blocks in 0 seconds, 0.00000000004330650 ms/block
info  2023-06-22T06:41:16.339 nodeos    chain_plugin.cpp:1115         plugin_startup       ] starting chain in read/write mode
info  2023-06-22T06:41:16.339 nodeos    chain_plugin.cpp:1123         plugin_startup       ] Blockchain started; head block is #60846139
info  2023-06-22T06:41:16.339 nodeos    account_query_db.cpp:143      build_account_query_ ] Building account query DB
info  2023-06-22T06:41:17.809 nodeos    account_query_db.cpp:163      build_account_query_ ] Finished building account query DB in 1.46961000000000008
info  2023-06-22T06:41:17.809 nodeos    chain_api_plugin.cpp:115      plugin_startup       ] starting chain_api_plugin
info  2023-06-22T06:41:17.810 nodeos    net_api_plugin.cpp:53         plugin_startup       ] starting net_api_plugin
info  2023-06-22T06:41:17.810 nodeos    producer_plugin.cpp:1227      plugin_startup       ] producer plugin:  plugin_startup() begin
info  2023-06-22T06:41:17.811 nodeos    producer_plugin.cpp:1259      plugin_startup       ] Launching block production for 1 producers at 2023-06-22T06:41:17.811.
info  2023-06-22T06:41:17.811 nodeos    producer_plugin.cpp:1283      plugin_startup       ] producer plugin:  plugin_startup() end
info  2023-06-22T06:41:17.811 nodeos    producer_api_plugin.cp:97     plugin_startup       ] starting producer_api_plugin
info  2023-06-22T06:41:17.811 nodeos    resource_monitor_plugi:115    plugin_startup       ] Creating and starting monitor thread
info  2023-06-22T06:41:17.811 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/blocks's file system to be monitored
info  2023-06-22T06:41:17.811 nodeos    file_space_handler.hpp:130    add_file_system      ] [path removed]/libre/mainnet/blocks's file system monitored. shutdown_available: 45 GiB, capacity: 459 GiB, threshold: 90%
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/blocks/retained's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/blocks/archive's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/blocks/reversible's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/state's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:130    add_file_system      ] [path removed]/libre/mainnet/state's file system monitored. shutdown_available: 21 GiB, capacity: 212 GiB, threshold: 90%
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/state-history's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/state-history/archive's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/state-history/retained's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/snapshots's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/protocol_features's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/state's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/blocks's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/state-history's file system to be monitored
info  2023-06-22T06:41:17.812 nodeos    file_space_handler.hpp:96     add_file_system      ] [path removed]/libre/mainnet/snapshots's file system to be monitored
info  2023-06-22T06:41:18.583 nodeos    platform_timer_accurac:62     compute_and_print_ti ] Checktime timer accuracy: min:2us max:40us mean:8us stddev:3us
info  2023-06-22T06:41:19.142 nodeos    producer_plugin.cpp:651       on_incoming_block    ] Received block beea0a8a08a3697e... #60847000 @ 2023-06-22T06:07:37.500 signed by librenodeone [trxs: 0, lib: 60846672, confirmed: 0, net: 0, cpu: 100, elapsed: 29, time: 768, latency: 2021642 ms]
info  2023-06-22T06:41:19.952 nodeos    producer_plugin.cpp:651       on_incoming_block    ] Received block c90415d8e40edc62... #60848000 @ 2023-06-22T06:15:57.500 signed by libremt [trxs: 1, lib: 60847668, confirmed: 0, net: 152, cpu: 200, elapsed: 149, time: 1829, latency: 1522452 ms]
info  2023-06-22T06:41:20.615 nodeos    producer_plugin.cpp:651       on_incoming_block    ] Received block 51e416df3486e2ba... #60849000 @ 2023-06-22T06:24:17.500 signed by interchainbp [trxs: 0, lib: 60848664, confirmed: 0, net: 0, cpu: 100, elapsed: 141, time: 1331, latency: 1023115 ms]
info  2023-06-22T06:41:21.274 nodeos    producer_plugin.cpp:651       on_incoming_block    ] Received block da8f50914e0586b3... #60850000 @ 2023-06-22T06:32:37.500 signed by interchainbp [trxs: 0, lib: 60849672, confirmed: 0, net: 0, cpu: 100, elapsed: 56, time: 1092, latency: 523774 ms]
info  2023-06-22T06:41:21.571 nodeos    producer_plugin.cpp:651       on_incoming_block    ] Received block 4c5f45cd657f1725... #60850449 @ 2023-06-22T06:36:22.000 signed by eosusa [trxs: 0, lib: 60850116, confirmed: 0, net: 0, cpu: 100, elapsed: 44, time: 451, latency: 299571 ms]
```

**Comment by CryptoBloks** [comment] 2023-06-22 18:09
[debug.out.log](https://github.com/AntelopeIO/leap/files/11837873/debug.out.log)
[debug.error.log](https://github.com/AntelopeIO/leap/files/11837874/debug.error.log)

**Comment by heifner** [comment] 2023-06-23 02:53
I have not been able to reproduce this. I do not have a large retain directory of blocks however.

It does scan all the files in the retain directory, but that behavior is unchanged since 4.0.0. If you are seeing fast startup with 4.0.1 and very slow with 4.0.3 does not seem like that would be the issue. 

Could you try without the retain directory and see if that makes a difference.

**Comment by CryptoBloks** [comment] 2023-06-23 05:50
> I have not been able to reproduce this. I do not have a large retain directory of blocks however.
> 
> It does scan all the files in the retain directory, but that behavior is unchanged since 4.0.0. If you are seeing fast startup with 4.0.1 and very slow with 4.0.3 does not seem like that would be the issue.
> 
> Could you try without the retain directory and see if that makes a difference.

Sure, I'll kick off a rebuild and resync and see if that makes a differnce.

**Comment by heifner** [comment] 2023-06-23 18:16
So you saw the same behavior with 4.0.1?

**Comment by CryptoBloks** [comment] 2023-06-23 18:38
> So you saw the same behavior with 4.0.1?

Not exactly.  When I dug in to the 4.0.1 servers, they had larger stride sizes (.5 mm blocks).  When I tested again last night using 4.0.3, same configs except a stride of .25mm blocks, the problem no longer exists... or at least it wasn't apparent to me.  The effort to repeat and apples to apples test isn't necessarily worth it.  I am willing to do it if you'd find the results useful... but I believe you when you say that the code function hasn't changed in this area between versions. 

It also seems, based partially on your explanation of how the code works above, that it's a issue of too many slice files in the retained blocks directory.  On review of the disk performance during startup, I'd guess that nodeos is only pulling in a small number of files at a time, and processing them, before moving on to the next batch.  Simple scaling, increase the amount of files by orders of magnitude, increase the load time by orders or magnitude.  Disk and CPU utilization during long startup was minimal, with no obvious bottlenecks at the system level.  It just seem that we can't implement small strides without a performance penalty on startup, as currently architected.

**Comment by heifner** [comment] 2023-06-23 18:55
Thanks that makes more sense.

After the log statement: `chain_state_history.log has blocks 60927001-60927245`. The code opens the log catalog which loops through every file in the `retained` directory:
https://github.com/AntelopeIO/leap/blob/v4.0.3/libraries/chain/include/eosio/chain/log_catalog.hpp#L88 to setup a collection of mappings for block num to log file. 

Seems we need to move that to on disk instead of re-creating it on every startup.

**Comment by CryptoBloks** [comment] 2023-06-23 18:56
> Seems we need to move that to on disk instead of re-creating it on every startup.

Yeah, that would be a good middle ground.

**Comment by heifner** [comment] 2023-07-07 18:18
What type of filesystem is your state-history store on?

**Comment by CryptoBloks** [comment] 2023-07-07 18:20
> What type of filesystem is your state-history stored on?

ZFS.  It's a zpool with 8 SSDs as pool members.

**Comment by heifner** [comment] 2023-07-07 18:36
Can you try: `time ls -l state-history/retained | wc` and report the results.

**Comment by CryptoBloks** [comment] 2023-07-07 18:50
`
/libre/mainnet$ time ls -l state-history/retained | wc
   1017    9146   95155

real    0m0.007s
user    0m0.002s
sys     0m0.007s
`

**Comment by heifner** [comment] 2023-07-07 19:27
> ```
> /libre/mainnet$ time ls -l state-history/retained | wc
>    1017    9146   95155
> 
> real    0m0.007s
> user    0m0.002s
> sys     0m0.007s
> ```
> 
> Also keep in mind that the original server has been rebuilt with a larger stride value - 250000 blocks. These results won't be an apples to apples comparison to the original issue.

With this # of files is your startup quick?

**Comment by CryptoBloks** [comment] 2023-07-07 21:42
> With this # of files is your startup quick?

Yes.

**Closed** 2023-07-11 13:38 UTC
Labels: bug, OCI, 👍 lgtm
