### ISSUE TITLE
prometheus nodeos_p2p_connections doesn't clean up connections that went away 5.0

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#1687] opened 2023-09-27 16:18 UTC
In our environment node A is connected to node B and vice-versa.  This means one of those connections is duplicate.  The nodes keep trying to reconnect.  

Prometheus has a view into all the connections.  This table is getting very long.

```
$ curl -s http://jungle4-dev11.mar.eosn.io:9101/v1/prometheus/metrics | grep eosn-jungle4-trxrly28:9876 | wc -l
340
```

or without the `wc`

```
...
nodeos_p2p_connections{connid_145="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_146="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_147="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_89="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_319="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_152="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_167="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_153="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_248="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_154="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_157="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_206="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_68="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_12="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_39="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_292="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_24="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_166="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
````

The old connection details need to be cleaned up much more aggressively.

**Comment by matthewdarwin** [comment] 2023-09-27 16:24
It is debatable as to if these duplicate connection things provide any value or not.  Maybe not export any detailed stats until it has been determined the connection is valid and not duplicate.

Add add a duplicate connection counter.

**Comment by heifner** [comment] 2023-09-27 16:28
Once #1683 is done then these would all be under `8c5a970`. Is it worth keeping if there is only one? Seems like that would be useful.

**Comment by matthewdarwin** [comment] 2023-09-27 16:58
Yes, seems more useful.  Especially if it has a duplicate counter specific to that peer. ;-) (more work of course for that)

**Comment by bhazzard** [comment] 2023-09-28 17:35
Likely caused by #1683 and solved with the same approach.

Closing as duplicate.

**Closed by bhazzard** 2023-09-28 17:35 UTC
Labels: bug, 👍 lgtm
