### ISSUE TITLE
get_table_by_scope returns a "more" value on eosio account

### ISSUE THREAD

**Issue by poplexity** [AntelopeIO/leap#608] opened 2022-12-30 19:59 UTC
On eosio account when you get scope against eosio tables which are scoped to eosio you will get an empty rows array but the more value is populated.  If you repeat this you will continue to get a different value for more.  If you pass that more value as lower_bound it doesn't have any rows.  If you pass eosio as the lower_bound you get expected results.  Doing the exact same thing with other non-eosio accounts has the expected result (has rows, does not have more)

![IMAGE 2022-12-30 11:57:39](https://user-images.githubusercontent.com/2374993/210107613-815d155e-54e1-42df-87d7-273d01f6ee97.jpg)
![IMAGE 2022-12-30 11:57:44](https://user-images.githubusercontent.com/2374993/210107624-54ac73fb-4e2d-4868-bd03-ccdd6b0cc67e.jpg)

**Comment by huangminghuang** [comment] 2023-02-24 18:47
This is the expected behavior. The way that `get scope` works is that it iterates through all the entries belong to the account, (in this case `eosio`) and then returns the entries match the requested table. The problem is that the `eosio` account has too many data in it, it couldn't finish iterating the entire table before it hits the time limit. Therefore, it returns a 'more' field to indicates where it stops before timeout. You should then use the `more` field as the lower bound to continue the search. 

For example:
```
$ cleos get scope  eosio -t voters
{
  "rows": [],
  "more": "1242231.eosn"
}
$ cleos get scope  eosio -t voters -L 1242231.eosn
{
  "rows": [],
  "more": "15dami.ftw"
}
$ cleos get scope  eosio -t voters -L 15dami.ftw
{
  "rows": [],
  "more": "1stadailyshy"
}
```

Eventually, you will get the result when the lower bound is close to where the requested data resides. That's also why you immediately get the result when you use `eosio` as lower bound because the scope of the first `voters` table for `eosio` account is exactly `eosio`. 

There are two approaches to alleviate the issue:
- External looping: write a scrip to invoke `cleos get scope` in a loop, each time uses the `more` field from previous result to start the next. Here is a shell script I came up with
```
#!/bin/bash

r=`cleos get scope eosio -t voters --time-limit 20`
while [[ $(echo "$r" | jq .rows) == "[]" ]]; do
	more=$(echo "$r" | jq -r .more)
	echo "$r"
	r=`cleos get scope eosio -t voters --time-limit 20 -L "$more"`
done
echo $r
```
- Changing time limit: start up your own `nodeos` with `--http-max-response-time-ms` to a very big value and then invoke `cleos` with `--time-limit` to a value slightly smaller than the  `http-max-response-time-ms`.

**Comment by stephenpdeos** [comment] 2023-04-17 14:54
Because this is working as expected and we've committed to a [documentation task](https://github.com/eosnetworkfoundation/devrel/issues/219) to further clarify, closing this for now

**Closed** 2023-04-17 14:54 UTC
Labels: documentation, 👍 lgtm, actionable
