### ISSUE TITLE
ship_streamer_test failure

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#2074] opened 2024-01-11 15:03 UTC
https://github.com/AntelopeIO/leap/actions/runs/7489977409/job/20388261708?pr=2073#step:4:642

**Comment by spoonincode** [comment] 2024-08-08 16:10
considering this a duplicate of AntelopeIO/spring#275 which is resolved in spring due to spring's ship being refactored

**Closed by spoonincode** 2024-08-08 16:10 UTC
Labels: 👍 lgtm, test-instability
