### ISSUE TITLE
why 404?

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [AntelopeIO/leap#344] opened 2022-10-18 12:28 UTC
Sometimes it lasts an hour and the request returns a 404，The result is like this：

{"code":404,"message":"Not Found","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"Unknown Endpoint","file":"http_plugin.cpp","line_number":590,"method":"handle_http_request"}]}}

Why？？？？

**Comment by heifner** [comment] 2022-10-18 12:31
Can you provide more information. What request are you making? Are you requesting a public or private nodeos? If private what is your command line and config.ini of nodeos?

**Comment by heifner** [comment] 2022-10-18 12:49
What was your curl command?

**Comment by zhaoxiangjunupi** [comment] 2022-10-18 12:54
> What was your curl command?

curl -i -X  http://127.0.0.1:8888/v1/chain/get_info

**Comment by heifner** [comment] 2022-10-18 13:11
What version of nodeos are you running?

**Comment by heifner** [comment] 2022-10-19 12:10
> > What version of nodeos are you running?
> 
> can you provide your config.ini file？

I see nothing wrong with your config.ini file. Going to test this and see if I can reproduce it.

**Comment by zhaoxiangjunupi** [comment] 2022-10-19 12:11
> > > What version of nodeos are you running?
> > 
> > 
> > can you provide your config.ini file？
> 
> I see nothing wrong with your config.ini file. Going to test this and see if I can reproduce it.

Thank you, please reply me if you find a problem

**Comment by heifner** [comment] 2022-10-19 12:47
> curl -i -X http://127.0.0.1:8888/v1/chain/get_info

Did you mean: `curl -i -X PUT http://127.0.0.1:8888/v1/chain/get_info`

**Comment by zhaoxiangjunupi** [comment] 2022-10-19 12:49
> > > curl -i -X http://127.0.0.1:8888/v1/chain/get_info
> > 
> > 
> > Did you mean: `curl -i -X PUT http://127.0.0.1:8888/v1/chain/get_info`
> 
> curl -i -X POST http://127.0.0.1:8888/v1/chain/get_info

curl -i -X GET http://127.0.0.1:8888/v1/chain/get_info

**Comment by zhaoxiangjunupi** [comment] 2022-10-19 12:50
> > > curl -i -X http://127.0.0.1:8888/v1/chain/get_info
> > 
> > 
> > Did you mean: `curl -i -X PUT http://127.0.0.1:8888/v1/chain/get_info`
> 
> curl -i -X POST http://127.0.0.1:8888/v1/chain/get_info

curl -i -X GET http://127.0.0.1:8888/v1/chain/get_info
error will occur

**Comment by heifner** [comment] 2022-10-19 13:00
Using your config.ini I was not able to reproduce this. Could you try v3.2.0-rc1 and see if that works for you? v3.2.0 includes a new implementation of the http_plugin using Boost Beast instead of WebSocket++.

**Comment by zhaoxiangjunupi** [comment] 2022-10-19 13:03
> Using your config.ini I was not able to reproduce this. Could you try v3.2.0-rc1 and see if that works for you? v3.2.0 includes a new implementation of the http_plugin using Boost Beast instead of WebSocket++.

ok i will try it, if there is any problem i will contact you, please keep in touch

**Comment by stephenpdeos** [comment] 2022-11-10 18:47
As per above comment 3 weeks ago, closing for now

**Closed by stephenpdeos** 2022-11-10 18:47 UTC
Labels: more-info
