### ISSUE TITLE
beast_http_session errors

### ISSUE THREAD

**Issue by jbuice** [AntelopeIO/leap#530] opened 2022-12-01 18:16 UTC
After upgrading from 3.1.3 to 3.2, I started seeing the following error pairs about 60 times per second.

```error 2022-12-01T18:06:50.893 http-1    beast_http_session.hpp:49     fail                 ] read: Connection reset by peer```
```error 2022-12-01T18:06:50.893 http-1    beast_http_session.hpp:50     fail                 ] closing connection```

This is happening on all the 3.2 API nodes taking localhost load-balanced http requests served through HAProxy for the Telos EVM at a rate of about 150 requests/second. 

Flow is:

Hyperion API -> HAProxy -> nodeos

Where Hyp API is running on one server and HAProxy and Nodeos are running together on another server.

**Comment by heifner** [comment] 2022-12-05 13:32
Marking as a bug although it is not clear there is actually anything wrong. Could just need to change the `error` level log to `debug` level logging for this particular case. Need to see if this can be reproduced.

**Comment by greg7mdp** [comment] 2023-02-23 16:25
@jbuice are you using https?

**Comment by greg7mdp** [comment] 2023-02-24 20:14
@jbuice , the reason  these messages are showing up in leap 3.2 is because the implementation of the http_server changed in leap 3.2, including adding support for HTTP 1.1 Keep-Alive, which allows HTTP connections to persist for more than one request. 

As a result, when the client closes the connection, the server is busy performing a read (waiting for the next request) which end with a `Connection reset by peer` error. This is reported as an error by mistake, as this is the expected behavior, so I will update the code to just close our side of the connection sliently.

Thanks for reporting the issue!

**Closed as completed** 2023-02-27 15:39 UTC
Labels: bug, good first issue, 👍 lgtm, actionable
