### ISSUE TITLE
Obtaining chain information multiple times in a row will occasionally encounter the problem of slow response from the interface

### ISSUE THREAD

**Issue by YuXiaoCoder** [AntelopeIO/leap#602] opened 2022-12-29 12:15 UTC
Obtaining chain information multiple times in a row will occasionally encounter the problem of slow response from the interface
```bash
curl -s -X POST http://127.0.0.1:8888/v1/chain/get_info | jq
{
  "server_version": "9efc569a",
  "chain_id": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
  "head_block_num": 286272347,
  "last_irreversible_block_num": 286272014,
  "last_irreversible_block_id": "11102a0eaef9e998c4c69cdc47ddf08bc9f95fe05cb5cf712b2d2e4d8acf3ebc",
  "head_block_id": "11102b5babf9c219e5bfd45aa932290a2fb14c92b8be4d2cb6f1f2ec2f3a56d4",
  "head_block_time": "2022-12-29T12:13:52.500",
  "head_block_producer": "atticlabeosb",
  "virtual_block_cpu_limit": 200000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 199348,
  "block_net_limit": 1048096,
  "server_version_string": "v3.2.0",
  "fork_db_head_block_num": 286272347,
  "fork_db_head_block_id": "11102b5babf9c219e5bfd45aa932290a2fb14c92b8be4d2cb6f1f2ec2f3a56d4",
  "server_full_version_string": "v3.2.0-9efc569ae5eed75a6dd6c6ada67ef80eb3bbf366",
  "total_cpu_weight": "383811718688790",
  "total_net_weight": "96313730812303",
  "earliest_available_block_num": 285004309,
  "last_irreversible_block_time": "2022-12-29T12:11:05.500"
}
```
![image](https://user-images.githubusercontent.com/26297513/209949441-b6623e9f-c094-48be-b97f-d9418e8e5eb2.png)

**Comment by linh2931** [comment] 2022-12-29 15:41
The `real` field is wall clock time spent by the command, which can be affected by other processes running on your server. The screenshot shows the same head block time for the two consecutive `get_info`s, indicating the RPC endpoint retrieved the information in time. 

Can you try using` cleos get info`, and `curl` without `jq`?

I could not reproduce the problem on my local `nodeos`.

**Comment by heifner** [comment] 2022-12-30 13:22
Are you syncing up to head of the chain during these `get_info` calls? Handling http requests is lower priority than consuming blocks so it can be delayed if nodeos is busy with other tasks.

**Comment by YuXiaoCoder** [comment] 2023-01-02 02:44
@linh2931 
I have the same problem using cleos get info, I suggest adding a query_time for it

**Comment by YuXiaoCoder** [comment] 2023-01-02 02:45
@heifner I have synced to the head of the chain

**Comment by YuXiaoCoder** [comment] 2023-01-02 02:52
@linh2931 I also have two other nodes, which have the same configuration, but only one of them will be delayed. I cannot replicate this problem in other nodes

**Comment by heifner** [comment] 2023-01-02 13:10
> I suggest adding a query_time for it

Can you explain, I don't know what you mean by this.

**Comment by heifner** [comment] 2023-01-02 13:11
> @linh2931 I also have two other nodes, which have the same configuration, but only one of them will be delayed. I cannot replicate this problem in other nodes

This seems rather odd. Any difference in hardware or what is running on the nodes?

**Comment by YuXiaoCoder** [comment] 2023-01-04 02:48
@heifner query_time is the time from when the node receives the request to when it returns the response

**Comment by YuXiaoCoder** [comment] 2023-01-04 02:49
@heifner I use k8s to run the nodes, and the resources given to them are exactly the same

**Comment by bhazzard** [comment] 2023-04-20 17:48
Closing for lack of actionable information.

**Closed by bhazzard** 2023-04-20 17:48 UTC
Labels: more-info
