### ISSUE TITLE
http requests fails with timeout on large block (`json.hpp` issue?)

### ISSUE THREAD

**Issue by greg7mdp** [AntelopeIO/leap#677] opened 2023-01-31 23:01 UTC
```
$ curl -X POST -d '{"block_num_or_id": 291953778}' http://localhost:8888/v1/chain/get_block
{"code":500,"message":"Internal Service Error","error":{"code":2,"name":"timeout_exception","what":"deadline 2023-01-31T22:14:07.564 exceeded by 914656us ","details":[{"message":"deadline 2023-01-31T22:14:07.564 exceeded by 914656us ","file":"json.hpp","line_number":63,"method":"operator()"}]}}#
```

in [eosq](https://eos.eosq.eosnation.io/block/1166dc72e60565f69a41c668adf227b4bf25988a4f0c36ccd406898ce000b906) block explorer.

The message mentions `json.hpp:63`, which is in a `string to_string()` function. Maybe we have an issue where creating json output takes excessively long for large trees?

**Comment by matthewdarwin** [comment] 2023-01-31 23:48
This works fine in nodeos 3.1.  So regression here.

**Comment by matthewdarwin** [comment] 2023-02-01 00:14
`http-max-response-time-ms = 2500` works

**Comment by matthewdarwin** [comment] 2023-02-01 03:37
Seems to be a deliberate but poorly documented change in https://github.com/AntelopeIO/leap/pull/96

**Comment by greg7mdp** [comment] 2023-02-01 12:10
> Seems to be a deliberate but poorly documented change in #96

Probably. Although the PR #96 doesn't list `get_block` as one of the affected APIs?

**Comment by matthewdarwin** [comment] 2023-02-01 12:35
I don't know why we would want to have limits on get_block.  If the block is stored and requested we want to send it.

**Comment by greg7mdp** [comment] 2023-02-01 12:41
My (limited) understanding is that if the node is used for block production, we may not want it failing to do so because its main thread is busy serving long http requests. If the node is used mainly for serving data requests, yes probably these limits should be relaxed.

**Comment by matthewdarwin** [comment] 2023-02-01 12:43
block production nodes should never be serving http requests anyway.

**Comment by heifner** [comment] 2023-02-01 12:44
> I don't know why we would want to have limits on get_block. If the block is stored and requested we want to send it.

So just set a very high limit on the api node. Or do you want to avoid long running `get_table` calls?

**Comment by bhazzard** [comment] 2023-02-03 16:55
In an ENF backlog refinement session, we discussed this issue at length, but didn’t come to a clear consensus on the best path forward.   We did all agree that the current behavior is undesirable and that more comprehensive thought is required around api architecture and where serialization should be handled. For now, we will simply communicate a workaround.

_The workaround:_
Ensure that max-http-response-time is configured to be greater than max-abi-serialization-time to prevent timeouts on GetBlock. To keep a lower maximum allowed http response time for endpoints other than GetBlock, run multiple nodeos instances with the required configurations, and use a proxy to direct to them as desired.


_A more complete statement with context:_
API endpoints often require ABI serialization. For large blocks requested with the GetBlock endpoint, this serialization can take quite a long time. To minimize the occurrence of requests that require a long running serialization failing due to exceeding the maximum allowed http response time our suggested workaround is to ensure that max-http-response-time is configured to be greater than max-abi-serialization-time.

If a node operator would like to keep a lower maximum allowed http response times for endpoints that don’t have this problem, one option is to use a proxy to direct GetBlock requests to a dedicated nodeos instance with a higher max-http-response-time, and all other requests to a nodeos instance with your preferred max-http-response-time.

**Comment by heifner** [comment] 2023-02-06 17:17
Time for the abi serializer to_variant vs the conversion to json.
```
to_variant calls: 1, total: 884855us, avg: 884855us
to json    calls: 1, total:  48551us, avg:  48551us
```

**Comment by greg7mdp** [comment] 2023-02-06 17:30
Well, I guess it shows that the issue, if there is one, is in `to_cariant`!

**Comment by heifner** [comment] 2023-02-06 17:36
> Well, I guess it shows that the issue, if there is one, is in `to_variant`!

Yeah, that is as expected. Although that to json is rather terrible as well.

**Comment by heifner** [comment] 2023-02-07 00:41
For reference the same block without exploding it via abi_serializer (what a `/v1/chain/get_raw_block` would be):

```
info  2023-02-07T00:40:21.876 nodeos    stopwatch.hpp:41              report               ] get_block calls: 1, total: 1460us, avg: 1460us
info  2023-02-07T00:40:21.878 http-0    stopwatch.hpp:41              report               ] convert to variant calls: 1, total: 1692us, avg: 1692us
info  2023-02-07T00:40:21.883 http-1    stopwatch.hpp:41              report               ] to json calls: 1, total: 4546us, avg: 4546us
```

**Comment by heifner** [comment] 2023-02-07 01:15
Move most of the abi_serialization off the main thread:

```
info  2023-02-07T01:12:34.801 nodeos    stopwatch.hpp:41              report               ] get_block calls: 1, total: 1817us, avg: 1817us
info  2023-02-07T01:12:34.802 nodeos    stopwatch.hpp:41              report               ] gather abis calls: 1, total: 742us, avg: 742us
info  2023-02-07T01:12:34.987 http-0    stopwatch.hpp:41              report               ] abi_serializer calls: 1, total: 184769us, avg: 184769us
info  2023-02-07T01:12:35.036 http-1    stopwatch.hpp:41              report               ] to json calls: 1, total: 46043us, avg: 46043us
```

**Comment by greg7mdp** [comment] 2023-02-07 01:32
Wow, did that speed up the abi serialization a lot? Above you reported that `to_variant` took `884855us`.

**Comment by heifner** [comment] 2023-02-07 01:36
> Wow, did that speed up the abi serialization a lot? Above you reported that `to_variant` took `884855us`.

Yes. This uses an abi cache so that an abi is only pulled out of chainbase and an abi_serializer created once per account. In the existing implementation that is done over and over again each time the account is referenced in the block.

**Comment by heifner** [comment] 2023-02-07 01:45
> OK, that makes more sense, looks like an great speedup, over 4x faster. So the speedup is because of the cache, not because it is done on a different thread.

I believe so, yes.

> I'll have to check out the cache you implemented. Is it a lru cache? And does it need to support concurrent access from multiple threads?

Nothing that complicated is used. The cache only lives for the life of the get_block call. Since the gather abi which creates the cache is less than 1ms in this example; I think that is fine as a final solution.

**Comment by heifner** [comment] 2023-02-08 14:15
Should we consider this closed by #696 ?

**Comment by greg7mdp** [comment] 2023-02-08 15:17
> Should we consider this closed by #696 ?

Yes, I think so. With your cache the request is is significantly faster so that should lessen the problem.
Also, I was wondering if you checked whether avoiding the extra string copies did speed up the `abi_serializer` part at all?

**Comment by heifner** [comment] 2023-02-08 15:37
> Also, I was wondering if you checked whether avoiding the extra string copies did speed up the `abi_serializer` part at all?

Yes, on my machine for the test block cut it in half.

**Comment by greg7mdp** [comment] 2023-02-08 15:41
Wow, that's great. So for that block, the request is about 8x faster than before your changes?

**Comment by heifner** [comment] 2023-02-08 15:48
The `abi_serializer` creation was only a small part of that.
```
info  2023-02-07T01:12:34.802 nodeos    stopwatch.hpp:41              report               ] gather abis calls: 1, total: 742us, avg: 742us
```
Now that is ~350us on my machine.

**Comment by greg7mdp** [comment] 2023-02-08 16:09
For having a good idea of the progress made in the PR, I think it would be very helpful if you provided the updated times for the following two measurements:

```
to_variant calls: 1, total: 884855us, avg: 884855us
to json    calls: 1, total:  48551us, avg:  48551us
```

**Comment by greg7mdp** [comment] 2023-02-08 16:14
> The `abi_serializer` creation was only a small part of that.

This must mean that the cache saves us a lot of duplicate  `abi_serializer` creations. And also that having a persistent cache as we discussed probably does not provide significant benefits (since creating the cache on-demand, even for this big block, costs little - 350us)

**Comment by heifner** [comment] 2023-02-08 16:28
Current PR perf:
```
info  2023-02-08T16:27:03.052 nodeos    stopwatch.hpp:50              report               ] create cache calls: 1, total: 310us, avg: 310us
info  2023-02-08T16:27:03.234 http-1    stopwatch.hpp:50              report               ] to variant calls: 1, total: 182242us, avg: 182242us
info  2023-02-08T16:27:03.281 http-0    stopwatch.hpp:50              report               ] to json calls: 1, total: 42802us, avg: 42802us
```
`to_variant` before would include `create cache` & `to variant`.

**Comment by greg7mdp** [comment] 2023-02-08 17:07
Great, so we are 5x faster on to_variant, 4x faster overall (including to_json). And almost all off the main thread. That is a great PR!

**Closed** 2023-02-15 13:24 UTC
Labels: discussion
